[project]
name = "installer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyunpack>=0.3",
    "pyyaml>=6.0.2",
    "requests>=2.32.5",
    "tomlkit>=0.13.3",
]
